"""Survey report generator — produces a Markdown + optional PDF report."""
from __future__ import annotations

import json
from datetime import datetime
from pathlib import Path
from typing import Dict, List

from utils.logger import get_logger

logger = get_logger(__name__)


class ReportGenerator:
    def __init__(self, session_dir: Path):
        self.session_dir = session_dir

    def generate(self, results: Dict, targets: List) -> str:
        md = self._build_markdown(results, targets)
        md_path = self.session_dir / "report.md"
        with open(md_path, "w") as f:
            f.write(md)
        logger.info(f"Report saved: {md_path}")

        # Attempt PDF if weasyprint available
        try:
            self._to_pdf(md, self.session_dir / "report.pdf")
            return str(self.session_dir / "report.pdf")
        except Exception as e:
            logger.debug(f"PDF generation skipped: {e}")
            return str(md_path)

    def _build_markdown(self, results: Dict, targets: List) -> str:
        now = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        lines = [
            "# Ocean Floor Survey Report",
            "",
            f"**Session ID:** `{results.get('session_id', 'N/A')}`  ",
            f"**Generated:** {now}",
            "",
            "---",
            "",
            "## Survey Summary",
            "",
        ]

        steps = results.get("steps", {})
        sonar = steps.get("sonar_load", {})
        gps = steps.get("gps_load", {})
        mosaic = steps.get("mosaic", {})
        det = steps.get("target_detection", {})

        lines += [
            f"| Parameter | Value |",
            f"|-----------|-------|",
            f"| Sonar files loaded | {sonar.get('files', 0)} |",
            f"| GPS points | {gps.get('points', 0)} |",
            f"| Mosaic dimensions | {mosaic.get('shape', ['?','?'])[0]} × {mosaic.get('shape', ['?','?'])[1 if len(mosaic.get('shape',[])) > 1 else 0]} px |",
            f"| Mosaic resolution | {mosaic.get('resolution_m', '?')} m/px |",
            f"| Targets detected | {det.get('count', 0)} |",
            "",
        ]

        bounds = gps.get("bounds", {})
        if bounds:
            lines += [
                "## Survey Area",
                "",
                f"- Lat: {bounds.get('min_lat','?'):.4f}° – {bounds.get('max_lat','?'):.4f}°N",
                f"- Lon: {bounds.get('min_lon','?'):.4f}° – {bounds.get('max_lon','?'):.4f}°W",
                "",
            ]

        lines += ["## Detected Targets", ""]
        if targets:
            lines += [
                "| ID | Class | Confidence | Lat | Lon | Est. Height (m) |",
                "|----|-------|-----------|-----|-----|-----------------|",
            ]
            for t in targets:
                d = t.to_dict()
                lines.append(
                    f"| {d['id']} | {d['classification'].upper()} | "
                    f"{d['confidence']*100:.0f}% | "
                    f"{d['lat'] or 'N/A'} | {d['lon'] or 'N/A'} | "
                    f"{d['estimated_height_m'] or 'N/A'} |"
                )
        else:
            lines.append("_No targets detected above threshold._")

        lines += [
            "",
            "## Output Files",
            "",
            f"- **Mosaic:** `{results.get('mosaic', 'N/A')}`",
            f"- **Targets JSON:** `{results.get('targets', 'N/A')}`",
            f"- **KML:** `{results.get('kml', 'N/A')}`",
            f"- **GeoTIFF:** `{results.get('geotiff', 'N/A')}`",
            "",
            "---",
            "_Report generated by Ocean Floor Mapper_",
        ]
        return "\n".join(lines)

    def _to_pdf(self, markdown_text: str, out_path: Path) -> None:
        import markdown  # type: ignore
        from weasyprint import HTML  # type: ignore
        html = markdown.markdown(markdown_text, extensions=["tables"])
        full_html = f"""
        <html><head><style>
        body {{ font-family: Arial, sans-serif; margin: 40px; color: #222; }}
        table {{ border-collapse: collapse; width: 100%; }}
        th, td {{ border: 1px solid #ccc; padding: 6px 10px; }}
        th {{ background: #1a3a5c; color: white; }}
        tr:nth-child(even) {{ background: #f5f5f5; }}
        h1 {{ color: #1a3a5c; }} h2 {{ color: #1a3a5c; border-bottom: 1px solid #ccc; }}
        </style></head><body>{html}</body></html>
        """
        HTML(string=full_html).write_pdf(str(out_path))
        logger.info(f"PDF report saved: {out_path}")
